# Generated by Django 4.2.6 on 2023-10-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ean_code', models.CharField(max_length=50)),
                ('image_name', models.CharField(max_length=200, null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
